{% set python_min = "3.11" %}
{% set name = "fancylog" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fancylog-{{ version }}.tar.gz
  sha256: fe772c29b999eb51fdd56f61033a762711d6277e5ccd7e02e6f31bab064152cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - packaging
    - python >={{ python_min }}
    - rich

test:
  imports:
    - fancylog
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adamltyson/fancylog
  summary: Fancier logging in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
    - JoeZiminski
