{% set name = "fancylog" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fancylog-{{ version }}.tar.gz
  sha256: 8606698149ea676a56f6a2667a1e60f910fd39b4babec05a39e020862791e361

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - packaging
    - python >={{ python_min }}
    - rich

test:
  imports:
    - fancylog
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adamltyson/fancylog
  summary: Fancier logging in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
    - JoeZiminski
