{% set name = "fancylog" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fancylog-{{ version }}.tar.gz
  sha256: 08edb5bbd69833962ec716df08518e80a02fa8db04ad8981c5705566875251e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - packaging
    - python >=3.6
    - rich

test:
  imports:
    - fancylog
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamltyson/fancylog
  summary: Fancier logging in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
